# Generated by Django 6.0.2 on 2026-03-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('education', 'Formation'), ('professionnel', 'Expérience professionnelle'), ('projet', 'Projet'), ('competition', 'Compétition'), ('certification', 'Certification')], default='education', max_length=20, verbose_name='Type')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre / Diplôme / Poste')),
                ('organisation', models.CharField(max_length=200, verbose_name='Organisation / École / Entreprise')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_debut', models.CharField(blank=True, max_length=50, null=True, verbose_name='Date de début (ex: 2023)')),
                ('date_fin', models.CharField(blank=True, max_length=50, null=True, verbose_name='Date de fin (ex: 2024 ou Présent)')),
                ('lieu', models.CharField(blank=True, max_length=150, null=True, verbose_name='Lieu')),
                ('technologies', models.JSONField(default=list, verbose_name='Technologies / Outils')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actuel', models.BooleanField(default=False, verbose_name='En cours (date_fin = Présent)')),
            ],
            options={
                'verbose_name': 'Expérience / Formation',
                'verbose_name_plural': 'Expériences / Formations',
                'ordering': ['ordre', '-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(max_length=100, verbose_name='Pays')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Région')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('google_maps_url', models.URLField(blank=True, null=True, verbose_name='Lien Google Maps')),
            ],
            options={
                'verbose_name': 'Localisation',
                'verbose_name_plural': 'Localisations',
            },
        ),
        migrations.CreateModel(
            name='PriseDeContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('sujet', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('lu', 'Lu'), ('repondu', 'Répondu'), ('archive', 'Archivé')], default='nouveau', max_length=20, verbose_name='Statut')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150, verbose_name='Titre')),
                ('description_courte', models.CharField(max_length=300, verbose_name='Description courte')),
                ('description_longue', models.TextField(blank=True, null=True, verbose_name='Description longue')),
                ('categorie', models.CharField(choices=[('fullstack', 'Full Stack'), ('backend', 'Backend'), ('frontend', 'Frontend'), ('data', 'Data / IA'), ('odoo', 'Odoo'), ('mobile', 'Mobile'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Catégorie')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('archive', 'Archivé')], default='termine', max_length=20, verbose_name='Statut')),
                ('technologies', models.JSONField(default=list, verbose_name='Technologies utilisées')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projets/', verbose_name='Image')),
                ('url_github', models.URLField(blank=True, null=True, verbose_name='Lien GitHub')),
                ('url_live', models.URLField(blank=True, null=True, verbose_name='Lien Live')),
                ('url_demo', models.URLField(blank=True, null=True, verbose_name='Lien Démo')),
                ('en_vedette', models.BooleanField(default=False, verbose_name='En vedette')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['ordre', '-date_fin'],
            },
        ),
        migrations.CreateModel(
            name='ReseauSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plateforme', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter / X'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Plateforme')),
                ('url', models.URLField(verbose_name='URL du profil')),
                ('icone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Classe icône (ex: fab fa-github)')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Réseau social',
                'verbose_name_plural': 'Réseaux sociaux',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150, verbose_name='Titre du service')),
                ('description', models.TextField(verbose_name='Description')),
                ('icone', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('data', 'Data / IA'), ('security', 'Sécurité'), ('devops', 'DevOps'), ('mobile', 'Mobile'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Icône / Catégorie')),
                ('numero', models.PositiveIntegerField(default=1, verbose_name='Numéro')),
                ('technologies', models.JSONField(default=list, verbose_name='Technologies / Outils')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['ordre'],
            },
        ),
    ]
